### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/boilerplate#13]

**Comment by aericson** [comment]
Use something like this:
```
deployment:
  staging:
    branch: develop
    commands:
      - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - git push git@heroku.com:{{project_name}}staging.git $CIRCLE_SHA1:refs/heads/master
      - heroku maintenance:on -a {{project_name}}-staging
      - heroku run python manage.py migrate -a {{project_name}}-staging
      - heroku maintenance:off -a {{project_name}}-staging
  production:
    branch: master
    commands:
      - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - heroku pg:backups capture -a {{project_name}}-production
      - git push git@heroku.{{project_name}}-production.git $CIRCLE_SHA1:refs/heads/master
      - heroku maintenance:on -a {{project_name}}-production
      - heroku run python manage.py migrate -a {{project_name}}-production
      - heroku maintenance:off -a {{project_name}}-production
```
